### ISSUE TITLE
Can you provide training and testing data

### ISSUE THREAD

**Issue by wmpscc** [jannctu/TIN#1]

**Comment by jannctu** [comment]
Hi, 

Thank you for your interest in our work. Please refer to the dataset from Dr. Liu http://mftp.mmcheng.net/liuyun/rcf/data/HED-BSDS.tar.gz,  and thanks to him for the data provided.

**Comment by xcc13** [comment]
Hello, thank you for your great work.
I downloded the data from  http://mftp.mmcheng.net/liuyun/rcf/data/HED-BSDS.tar.gz.
But when I tried to test with the pretrained model 'TIN2', an error occured like this .   It seems there are something lost in 'test_pair.lst'.




D:\Python\Anaconda\envs\pytorch\python.exe "D:\Python\Pycharm\PyCharm Community Edition 2019.2\helpers\pydev\pydevd.py" --multiproc --qt-support=auto --client 127.0.0.1 --port 56168 --file H:/Code/TIN-master/inference.py
pydev debugger: process 12380 is connecting

Connected to pydev debugger (build 192.5728.105)
Traceback (most recent call last):
  File "D:\Python\Pycharm\PyCharm Community Edition 2019.2\helpers\pydev\pydevd.py", line 2060, in <module>
    main()
  File "D:\Python\Pycharm\PyCharm Community Edition 2019.2\helpers\pydev\pydevd.py", line 2054, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "D:\Python\Pycharm\PyCharm Community Edition 2019.2\helpers\pydev\pydevd.py", line 1405, in run
    return self._exec(is_module, entry_point_fn, module_name, file, globals, locals)
  File "D:\Python\Pycharm\PyCharm Community Edition 2019.2\helpers\pydev\pydevd.py", line 1412, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "D:\Python\Pycharm\PyCharm Community Edition 2019.2\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "H:/Code/TIN-master/inference.py", line 43, in <module>
    for i, (image, ori, img_files) in enumerate(test_loader):
  File "D:\Python\Anaconda\envs\pytorch\lib\site-packages\torch\utils\data\dataloader.py", line 582, in __next__
    return self._process_next_batch(batch)
  File "D:\Python\Anaconda\envs\pytorch\lib\site-packages\torch\utils\data\dataloader.py", line 608, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
ValueError: Traceback (most recent call last):
  File "D:\Python\Anaconda\envs\pytorch\lib\site-packages\torch\utils\data\_utils\worker.py", line 99, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "D:\Python\Anaconda\envs\pytorch\lib\site-packages\torch\utils\data\_utils\worker.py", line 99, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "H:\Code\TIN-master\datasets.py", line 56, in __getitem__
    img_file, lb_file = self.filelist[index].split()
ValueError: not enough values to unpack (expected 2, got 1)

Process finished with exit code 1

**Comment by jannctu** [comment]
Hi @xcc13 

thank you for your interest in our work. 
I slightly modify the test_pair.lst. I added the ground-truth of each test image as the second argument (on test_pair.lst).

**Comment by xcc13** [comment]
> Hi @xcc13
> 
> thank you for your interest in our work.
> I slightly modify the test_pair.lst. I added the ground-truth of each test image as the second argument (on test_pair.lst).


Thank you very much. I will retry later.
By the way, do you know how to make the edge color darker?
I tested on my own data(the human brain) , but the result is not clear. We can only see the blurry outline.


![image](https://user-images.githubusercontent.com/46668415/87932494-303b2180-cabe-11ea-8cfc-5acaedcfef21.png)
